/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'taka__000' at '16/07/31 17:51' with Gradle 2.14
 *
 * @author taka__000, @date 16/07/31 17:51
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
